language: julia
sudo: false
os:
  - linux
julia:
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("GlobalSearchRegressionGUI")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'using Pkg; Pkg.add("Documenter")'
  - julia -e 'using Pkg; cd(Pkg.dir("GlobalSearchRegressionGUI")); include(joinpath("docs", "make.jl"))'
